name: base                                                                   
channels:                                                                    
  - defaults              
  - conda-forge                                                    
dependencies:                                                                
  - pandas
  - scikit-learn
  - fastapi
  - uvicorn
  - pydantic