name: base                                                                   
channels:                                                                    
  - defaults              
  - conda-forge                                                    
dependencies:                                                                
  - streamlit
  - requests